version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kiu_website
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
    command: npm run dev -- --turbo

  tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: kiu_tests
    depends_on:
      - web
    environment:
      APP_URL: http://web:3000
